/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainpackage;


import java.util.ArrayList;


import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Tolga
 */
public class TolgaTezel_PatternSearch extends javax.swing.JFrame {

    /**
     * Creates new form PatternSearch
     */
    public TolgaTezel_PatternSearch() {

        initComponents();
        this.setTitle("Tolga Tezel Pattern Search" );
        
        metinArea.setLineWrap(true);
        metinArea.setWrapStyleWord(true);
      
        cevapArea.setLineWrap(true);
        cevapArea.setWrapStyleWord(true);

        cevapArea.setEditable(false);
        
         metinArea.setText("11 Ayın Sultanı Ramazan , Hoşgeldin ya Şehri Ramazan ");
         desenField.setText("(Ramazan)");
        regexp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        cevapArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        metinArea = new javax.swing.JTextArea();
        desenField = new javax.swing.JTextField();
        AraButon = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        outputLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        combo1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        combo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose an Option", "Questions", "Answers" }));
        combo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo1İtemStateChanged(evt);
            }
        });

        cevapArea.setColumns(20);
        cevapArea.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cevapArea.setRows(5);
        jScrollPane1.setViewportView(cevapArea);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("TEXT");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("PATTERN");

        metinArea.setColumns(20);
        metinArea.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        metinArea.setRows(5);
        jScrollPane2.setViewportView(metinArea);

        desenField.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        AraButon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AraButon.setText("SEARCH");
        AraButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AraButonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("OUTPUT");

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose a Text", "Short length", "Medium length", "Long length", "Text with Numbers", "Random text 1", "Random text 2" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1İtemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Text Examples ");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Pattern Searcher");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Tolga TEZEL - JAVA");

        outputLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        outputLabel.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(combo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(161, 161, 161)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(desenField)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AraButon))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                    .addComponent(jLabel6))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 77, Short.MAX_VALUE)
                                .addComponent(AraButon))
                            .addComponent(jScrollPane2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(desenField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(31, 31, 31)
                                .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AraButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AraButonActionPerformed
    regexp();

    }//GEN-LAST:event_AraButonActionPerformed
public void regexp(){
         outputLabel.setText("");
        String metin1 = null;

        try {
            String metin = "<html>" + metinArea.getText() + "</html>";
            String pat = desenField.getText();
            Pattern r = Pattern.compile(pat);
            Matcher m = r.matcher(metin);
            ArrayList<String> liste = new ArrayList<>();

            while (m.find()) {
                if (!liste.contains(metin.substring(m.start(), m.end()))) {
                    liste.add(metin.substring(m.start(), m.end()));
                }
            }

            for (String s : liste) {

                metin = metin.replace(s, "<font color='red'>" + s + "</font>");
                
            }

             outputLabel.setText( metin );
        } catch (Exception e) {

        }

}
    private void jComboBox1İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1İtemStateChanged
        // TODO add your handling code here://PatternSyntaxException throw yap
        if (jComboBox1.getSelectedIndex() == 1) {
            metinArea.setText("Sunset is the time of day when our sky meets the outer space solar winds. There are blue, pink, and purple swirls, spinning and twisting, like clouds of balloons caught in a blender. The sun moves slowly to hide behind the line of horizon, while the moon races to take its place in prominence atop the night sky.");
        } else if (jComboBox1.getSelectedIndex() == 2) {
            metinArea.setText("Here is the perfect system for cleaning your room. First, move all of the items that do not have a proper place to the center of the room. Get rid of at least five things that you have not used within the last year. Take out all of the trash, and place all of the dirty dishes in the kitchen sink. Now find a location for each of the items you had placed in the center of the room. For any remaining items, see if you can squeeze them in under your bed or stuff them into the back of your closet. See, that was easy!");
        } else if (jComboBox1.getSelectedIndex() == 3) {
            metinArea.setText("The Blue Whales just played their first baseball game of the new season; I believe there is much to be excited about. Although they lost, it was against an excellent team that had won the championship last year. The Blue Whales fell behind early but showed excellent teamwork and came back to tie the game. The team had 15 hits and scored 8 runs. That’s excellent! Unfortunately, they had 5 fielding errors, which kept the other team in the lead the entire game. The game ended with the umpire making a bad call, and if the call had gone the other way, the Blue Whales might have actually won the game. It wasn’t a victory, but I say the Blue Whales look like they have a shot at the championship, especially if they continue to improve.");
        } else if (jComboBox1.getSelectedIndex() == 4) {
            metinArea.setText("It was July 21, 1969, and Neil Armstrong awoke with a start. It was the day he would become the first human being to ever walk on the moon. The journey had begun several days earlier, when on July 16th, the Apollo 11 launched from Earth headed into outer space. On board with Neil Armstrong were Michael Collins and Buzz Aldrin. The crew landed on the moon in the Sea of Tranquility a day before the actual walk. Upon Neil’s first step onto the moon’s surface, he declared, “That’s one small step for man, one giant leap for mankind.” It sure was!");
        } else if (jComboBox1.getSelectedIndex() == 5) {
            metinArea.setText("Silence should be safe. Silence should tell him, even in the dark, that nothing approached him, that nothing nearby could hurt him. Nonetheless, he began to long for noise, especially for the noise of straight-forward confrontation. To fight an enemy directly would be a blessing compared to stumbling blind, searching for the voiceless, incoporeal monstrosity the already nearly destroyed him twice.");
        } else if (jComboBox1.getSelectedIndex() == 6) {
            metinArea.setText("When at last he saw her, a Wednesday morning’s rain dripped from the maples, and what the sleepless nights had rehearsed flew out of his mind, leaving him empty and lost, as though part of his soul had been torn out and fashioned into the dark-haired woman who wore a raincoat and held an umbrella, who hesitated on the steps then slowly approached him, reading in his eyes the words he could never have found to say. ");
        }
    }//GEN-LAST:event_jComboBox1İtemStateChanged

    private void combo1İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo1İtemStateChanged
        // TODO add your handling code here:
        if (combo1.getSelectedIndex() == 1) {
            cevapArea.setText(
                    "Q1) Type a pattern to search for vowels on text. \n"
                    + "Q2) Type a pattern to search for hexadecimal letters on text. \n"
                    + "Q3) Type a pattern to search for consonants on text. \n"
                    + "Q4) Type a pattern to search for spaces on text. \n"
                    + "Q5) Type a pattern to search for everything on text. \n"
            );
        } else if (combo1.getSelectedIndex() == 2) {
            cevapArea.setText("First of all, let's start with the questions I gave on the site \n  "
                    + "Answer of Q1) : (67414) \n"
                    + "Answer of Q2) :[^aghtr] \n"
                    + "Answer of Q3) :(baba) or (ba){2} \n"
                    + "Answer of Q4) :[[.,!]] \n"
                    + "\n"
                    + "\n"
                    + "Secondly , The answers to the questions in this program are attached."
                    + "Answer of Q1) [aeiou]  \n"
                    + "Answer of Q2) [A-F] \n"
                    + "Answer of Q3) [^aeiou ] \n"
                    + "Answer of Q4) [ ] \n"
                    + "Answer of Q5) (.) \n"
                    + "There are multiple answers for those questions so Dont worry If your answers are not same with mines :) \n"
            );

        }
    }//GEN-LAST:event_combo1İtemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TolgaTezel_PatternSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TolgaTezel_PatternSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TolgaTezel_PatternSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TolgaTezel_PatternSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TolgaTezel_PatternSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AraButon;
    private javax.swing.JTextArea cevapArea;
    private javax.swing.JComboBox combo1;
    private javax.swing.JTextField desenField;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea metinArea;
    private javax.swing.JLabel outputLabel;
    // End of variables declaration//GEN-END:variables
}
